export const STORY_SCENARIOS = [
  // --- MEVCUT 10 ---
  { characters: ['Kaptan Bulut', 'Martı Gümüş'], prompt: 'Kaptan Bulut ve yardımcısı Martı Gümüş, gökyüzündeki gökkuşağının renklerinin neden solduğunu bulmak için renkli bir yolculuğa çıkıyor.', voice: 'Alnilam', voiceName: 'Yüce Kral', genre: 'adventure', style: 'watercolor', age: '4-6', language: 'tr' },
  { characters: ['Robot Çark', 'Küçük Mühendis Melis'], prompt: 'Robot Çark ve Melis, bozulan bir yıldız haritasını tamir etmek için uzay gemileriyle Samanyolu galaksisinde gizemli bir parçanın peşine düşerler.', voice: 'Iapetus', voiceName: 'Orman Muhafızı', genre: 'sci_fi', style: 'pixar', age: '6-10', language: 'tr' },
  { characters: ['Sevimli Ayı Pofuduk', 'Bilge Baykuş'], prompt: 'Ayı Pofuduk, kış uykusuna yatmadan önce ormandaki en büyük bal kovanının haritasını bulmak için Bilge Baykuş ile bir maceraya atılır.', voice: 'Aoede', voiceName: 'Bilge Anne', genre: 'tale', style: 'pastel', age: '2-4', language: 'tr' },
  { characters: ['Prenses Ada', 'Uçan At Kanat'], prompt: 'Prenses Ada, krallığın üzerinden hiç eksilmeyen yağmur bulutlarını dağıtmak için Uçan Atı Kanat ile güneşin doğduğu diyara uçar.', voice: 'Gacrux', voiceName: 'Gizemli Prenses', genre: 'fantasy', style: 'anime', age: '6-10', language: 'tr' },
  { characters: ['Minik Tavşan Pamuk', 'Hızlı Kaplumbağa'], prompt: 'Pamuk ve Kaplumbağa, ormanda düzenlenen yıllık büyük piknik için en lezzetli havuçları toplamak üzere gizli bahçeye giderler.', voice: 'Algenib', voiceName: 'Gezgin Tavşan', genre: 'fable', style: 'watercolor', age: '1-2', language: 'tr' },
  { characters: ['Cesur İtfaiyeci Kerem', 'Yavru Kedi Duman'], prompt: 'İtfaiyeci Kerem, bir ağacın en tepesinde mahsur kalan Duman\'ı kurtarmaya çalışırken, ikisi birden sihirli bir tünelden başka bir diyara geçerler.', voice: 'Algieba', voiceName: 'Cesur Şövalye', genre: 'adventure', style: 'cartoon', age: '4-6', language: 'tr' },
  { characters: ['Dedektif Can', 'Konuşan Köpek Tarçın'], prompt: 'Dedektif Can ve Tarçın, müzedeki en değerli elmasın neden sadece geceleri parladığını çözmek için gizemli bir ipucunu takip ederler.', voice: 'Callirrhoe', voiceName: 'Masalcı Kadın', genre: 'adventure', style: 'pop_art', age: '10-13', language: 'tr' },
  { characters: ['Minik Peri Işıltı', 'Dev Arı Vızvız'], prompt: 'Peri Işıltı, kanatlarındaki tozun azalması üzerine, dünyanın en nadir çiçeğinden polen toplamak için Dev Arı Vızvız\'ın sırtında bir yolculuğa çıkar.', voice: 'Fenrir', voiceName: 'Sihirli Peri', genre: 'tale', style: 'oil', age: '2-4', language: 'tr' },
  { characters: ['Süper Çocuk Mert', 'Gölge Adam'], prompt: 'Mert, şehri ele geçirmeye çalışan Gölge Adam\'ı iyilik ve neşe ile durdurmak için mahalledeki tüm çocuklarla bir plan yapar.', voice: 'Charon', voiceName: 'Heyecanlı Baba', genre: 'fantasy', style: 'pixar', age: '6-10', language: 'tr' },
  { characters: ['Mavi Ejderha Alev', 'Küçük Viking'], prompt: 'Alev, ateş püskürtemediği için üzüldüğünde, Küçük Viking ona acı biberlerin ve dostluğun sırrını anlatarak yardım eder.', voice: 'Achird', voiceName: 'Bilge Dede', genre: 'tale', style: 'retro', age: '4-6', language: 'tr' },

  // --- YENİ 40 SENARYO ---
  { characters: ['Uzaylı Zıpzıp', 'Astronot Kerem'], prompt: 'Zıpzıp, Ay üzerinde kaybolan sihirli antenini bulmak için Kerem ile kraterlerin arasında saklambaç oynar.', voice: 'Algenib', voiceName: 'Gezgin Tavşan', genre: 'sci_fi', style: 'pixar', age: '4-6', language: 'tr' },
  { characters: ['Uçan Araba Vınvın', 'Tamirci Ece'], prompt: 'Vınvın\'ın motoru gökkuşağı yakıtı bittiği için durur, Ece ona en tatlı meyve sularından yeni bir yakıt icat eder.', voice: 'Fenrir', voiceName: 'Sihirli Peri', genre: 'sci_fi', style: 'pop_art', age: '6-10', language: 'tr' },
  { characters: ['Zaman Yolcusu Arda', 'Dinozor Dino'], prompt: 'Arda, yanlışlıkla milyonlarca yıl geriye gidip Dino ile meyve toplama yarışı yapar.', voice: 'Charon', voiceName: 'Heyecanlı Baba', genre: 'sci_fi', style: 'oil', age: '6-10', language: 'tr' },
  { characters: ['Akıllı Ev Robi', 'Küçük Ali'], prompt: 'Robi, Ali\'nin ödevlerini yaparken bir hata yapar ve evin tüm eşyaları havada süzülmeye başlar.', voice: 'Achird', voiceName: 'Bilge Dede', genre: 'sci_fi', style: 'cartoon', age: '4-6', language: 'tr' },
  { characters: ['Yıldız Gemisi Kaptanı', 'Işık Hızı'], prompt: 'Kaptan, Samanyolu\'nun en uzak köşesindeki dondurma gezegenini bulmak için rota çizer.', voice: 'Alnilam', voiceName: 'Yüce Kral', genre: 'sci_fi', style: 'anime', age: '10-13', language: 'tr' },
  { characters: ['Siber Kedi Miya', 'Bilgisayar Faresi Tık'], prompt: 'Miya ve Tık, internet dünyasındaki kayıp bir klasörün içinde saklanan dijital balıkları kurtarırlar.', voice: 'Despina', voiceName: 'Huzur Perisi', genre: 'sci_fi', style: 'pop_art', age: '6-10', language: 'tr' },
  { characters: ['Gezegen Muhafızı', 'Ay Tozu'], prompt: 'Muhafız, Satürn\'ün halkalarından birinin düştüğünü fark eder ve onu yerine takmak için dev bir vinç icat eder.', voice: 'Iapetus', voiceName: 'Orman Muhafızı', genre: 'sci_fi', style: 'pixar', age: '10-13', language: 'tr' },
  { characters: ['Marslı Maviş', 'Dünyalı Doğa'], prompt: 'Maviş, Dünya\'daki çiçeklerin nasıl bu kadar güzel koktuğunu öğrenmek için gizlice bir bahçeye iner.', voice: 'Kore', voiceName: 'Gökkuşağı Kızı', genre: 'sci_fi', style: 'pastel', age: '4-6', language: 'tr' },
  { characters: ['Geleceğin Çocuğu', 'Hologram Dostum'], prompt: 'Hologram dostum, sadece hayal gücüyle çalışan bir oyun odası tasarlar ve çocuklar orada sınırları zorlar.', voice: 'Algieba', voiceName: 'Cesur Şövalye', genre: 'sci_fi', style: 'retro', age: '6-10', language: 'tr' },
  { characters: ['Güneş Paneli Panpa', 'Bulut Can'], prompt: 'Panpa, bulutlar güneşi kapattığında üzülür, Bulut Can ona komik şakalar yaparak dağılmasını sağlar.', voice: 'Algenib', voiceName: 'Gezgin Tavşan', genre: 'sci_fi', style: 'watercolor', age: '2-4', language: 'tr' },

  // MASAL (10 Yeni)
  { characters: ['Uykucu Bulut', 'Güneş Işığı'], prompt: 'Uykucu Bulut, sabah uyandığında her yerin neden parladığını merak eder ve Güneş Işığı ile tanışır.', voice: 'Aoede', voiceName: 'Bilge Anne', genre: 'tale', style: 'pastel', age: '0-1', language: 'tr' },
  { characters: ['Konuşan Ağaç Meşe', 'Küçük Sincap'], prompt: 'Meşe, ormanın en eski sırrını minik sincaba anlatırken rüzgarın şarkısını söyler.', voice: 'Achird', voiceName: 'Bilge Dede', genre: 'tale', style: 'oil', age: '4-6', language: 'tr' },
  { characters: ['Kayıp Anahtar', 'Gizemli Sandık'], prompt: 'Sandık, içindeki mutluluk iksirini paylaşmak için doğru anahtarı beklemektedir.', voice: 'Despina', voiceName: 'Huzur Perisi', genre: 'tale', style: 'watercolor', age: '6-10', language: 'tr' },
  { characters: ['Gökkuşağı Perisi', 'Renkler'], prompt: 'Peri, yağmurdan sonra renklerin birbirine karıştığını görür ve onları sıraya dizmek için dans eder.', voice: 'Fenrir', voiceName: 'Sihirli Peri', genre: 'tale', style: 'pastel', age: '2-4', language: 'tr' },
  { characters: ['Pamuk Şeker Bulutu', 'Tatlı Yağmur'], prompt: 'Bulut, çocuklara şekerleme yağdırmak ister ama önce bulutlar okulundan izin alması gerekir.', voice: 'Kore', voiceName: 'Gökkuşağı Kızı', genre: 'tale', style: 'anime', age: '4-6', language: 'tr' },
  { characters: ['Ay Dede', 'Yıldız Çocuklar'], prompt: 'Ay Dede, her gece çocuklara masallar anlatırken yıldızlar da gökyüzünde ışık saçarak ona eşlik eder.', voice: 'Aoede', voiceName: 'Bilge Anne', genre: 'tale', style: 'retro', age: '1-2', language: 'tr' },
  { characters: ['Sihirli Pabuçlar', 'Koşucu Kaya'], prompt: 'Pabuçlar, Kaya\'nın çok yavaş olduğunu görünce ona hız kazandırmak için büyü yaparlar.', voice: 'Callirrhoe', voiceName: 'Masalcı Kadın', genre: 'tale', style: 'cartoon', age: '4-6', language: 'tr' },
  { characters: ['Kristal Saray Prensi', 'Buzdan At'], prompt: 'Prens, sarayının neden eridiğini bulmak için kuzey ışıklarının peşinden gider.', voice: 'Alnilam', voiceName: 'Yüce Kral', genre: 'tale', style: 'anime', age: '6-10', language: 'tr' },
  { characters: ['Minik Dev', 'Kocaman Cüce'], prompt: 'Dünyanın en tatlı devi ve en güçlü cücesi, arkadaşlığın boyla ilgili olmadığını kanıtlar.', voice: 'Charon', voiceName: 'Heyecanlı Baba', genre: 'tale', style: 'pixar', age: '4-6', language: 'tr' },
  { characters: ['Dilek Ağacı', 'Yaprak'], prompt: 'Ağaç, üzerinden düşen her yaprağın bir çocuğun dileğini gerçekleştirdiğini fark eder.', voice: 'Iapetus', voiceName: 'Orman Muhafızı', genre: 'tale', style: 'oil', age: '6-10', language: 'tr' },

  // MACERA (10 Yeni)
  { characters: ['Hazine Avcısı Efe', 'Harita'], prompt: 'Efe, odasında bulduğu eski haritanın aslında mutfağa giden yolu gösterdiğini keşfeder ama yolda engeller vardır.', voice: 'Algieba', voiceName: 'Cesur Şövalye', genre: 'adventure', style: 'cartoon', age: '6-10', language: 'tr' },
  { characters: ['Denizaltı Kaptanı', 'Balık Memo'], prompt: 'Kaptan ve Memo, okyanusun en derinindeki kayıp şehri bulmak için ışıklı fenerlerini yakarlar.', voice: 'Iapetus', voiceName: 'Orman Muhafızı', genre: 'adventure', style: 'pixar', age: '6-10', language: 'tr' },
  { characters: ['Dağcı Kerem', 'Zirve Kartalı'], prompt: 'Kerem, dünyanın en yüksek dağına tırmanırken kartalın ona verdiği tüylerle uçmayı öğrenir.', voice: 'Alnilam', voiceName: 'Yüce Kral', genre: 'adventure', style: 'oil', age: '10-13', language: 'tr' },
  { characters: ['Orman Kaşifi Aslı', 'Maymun Muzmuz'], prompt: 'Aslı ve Muzmuz, aslan kralın kayıp tacını bulmak için sarmaşıklardan atlarlar.', voice: 'Callirrhoe', voiceName: 'Masalcı Kadın', genre: 'adventure', style: 'anime', age: '4-6', language: 'tr' },
  { characters: ['Bisikletli Postacı', 'Hızlı Rüzgar'], prompt: 'Postacı, tüm paketleri vaktinde yetiştirmek için rüzgarla yarışır ve her eve bir gülümseme götürür.', voice: 'Charon', voiceName: 'Heyecanlı Baba', genre: 'adventure', style: 'pop_art', age: '6-10', language: 'tr' },
  { characters: ['Kampçı Tayfası', 'Ateş Böceği'], prompt: 'Çocuklar gece kamp yaparken ateş böceklerinin aslında ormanın fenerleri olduğunu öğrenirler.', voice: 'Despina', voiceName: 'Huzur Perisi', genre: 'adventure', style: 'watercolor', age: '4-6', language: 'tr' },
  { characters: ['Uçurtma Avcısı', 'Kuyruklu Yıldız'], prompt: 'Uçurtma, rüzgara kapılıp gökyüzünün en tepesine çıkar ve bir kuyruklu yıldızla arkadaş olur.', voice: 'Kore', voiceName: 'Gökkuşağı Kızı', genre: 'adventure', style: 'pastel', age: '6-10', language: 'tr' },
  { characters: ['Balonla Seyahat', 'Bulutlar'], prompt: 'Renkli dev balon, dünyanın etrafını bir günde gezmek için rüzgar akıntılarını takip eder.', voice: 'Algenib', voiceName: 'Gezgin Tavşan', genre: 'adventure', style: 'pixar', age: '4-6', language: 'tr' },
  { characters: ['Safari Rehberi', 'Yavru Fil'], prompt: 'Rehber, sürüsünden ayrılan yavru fili annesine kavuşturmak için ormanın derinliklerine dalar.', voice: 'Achird', voiceName: 'Bilge Dede', genre: 'adventure', style: 'retro', age: '6-10', language: 'tr' },
  { characters: ['Yelkenli Kaptanı', 'Yunus Dostu'], prompt: 'Kaptan, fırtınadan kaçarken yunusların ona yol gösterdiğini fark eder ve güvenli bir liman bulur.', voice: 'Algieba', voiceName: 'Cesur Şövalye', genre: 'adventure', style: 'oil', age: '10-13', language: 'tr' },

  // FABL & FANTASTİK (10 Yeni)
  { characters: ['Bilge Kaplumbağa', 'Tavşan Hızlı'], prompt: 'Kaplumbağa, Tavşan\'a hızın değil sabrın kazandırdığını orman olimpiyatlarında bir kez daha gösterir.', voice: 'Achird', voiceName: 'Bilge Dede', genre: 'fable', style: 'watercolor', age: '4-6', language: 'tr' },
  { characters: ['Kibirli Aslan', 'Minik Fare'], prompt: 'Aslan, ağa yakalandığında minik farenin onu kurtarabileceğine asla inanmazdı ama gerçek dostluk kazandı.', voice: 'Alnilam', voiceName: 'Yüce Kral', genre: 'fable', style: 'retro', age: '2-4', language: 'tr' },
  { characters: ['Şarkıcı Ağustos Böceği', 'Çalışkan Karınca'], prompt: 'Böcek, kış geldiğinde karıncanın hazırlıklarının ne kadar değerli olduğunu bir şarkıyla anlatır.', voice: 'Kore', voiceName: 'Gökkuşağı Kızı', genre: 'fable', style: 'cartoon', age: '4-6', language: 'tr' },
  { characters: ['Yalancı Çoban', 'Kuzu Dostum'], prompt: 'Çoban, dürüstlüğün ne kadar önemli olduğunu kuzu dostuyla yaşadığı küçük bir olayla anlar.', voice: 'Charon', voiceName: 'Heyecanlı Baba', genre: 'fable', language: 'tr', style: 'oil', age: '6-10' },
  { characters: ['Sihirli Kütüphaneci', 'Kitap Canavarı'], prompt: 'Kütüphaneci, kitapların içinden fırlayan hikayelerin odaya dağılmasını engellemek için sihirli bir şiir okur.', voice: 'Aoede', voiceName: 'Bilge Anne', genre: 'fantasy', style: 'anime', age: '10-13', language: 'tr' },
  { characters: ['Ejderha Yavrusu', 'Ateş Püskürtemeyen'], prompt: 'Yavru ejderha, ateş yerine gökkuşağı püskürttüğünü fark edince tüm köyün neşesi olur.', voice: 'Fenrir', voiceName: 'Sihirli Peri', genre: 'fantasy', style: 'pixar', age: '4-6', language: 'tr' },
  { characters: ['Görünmez Çocuk', 'Boya Kovası'], prompt: 'Çocuk, bir boya kovasına çarpınca herkes onu görmeye başlar ve en komik saklambaç oyunu yaşanır.', voice: 'Callirrhoe', voiceName: 'Masalcı Kadın', genre: 'fantasy', style: 'pop_art', age: '6-10', language: 'tr' },
  { characters: ['Konuşan Kediler Krallığı', 'Süt Gölü'], prompt: 'Kediler, krallıklarındaki süt gölünün neden kuruduğunu bulmak için süt yoluna çıkarlar.', voice: 'Despina', voiceName: 'Huzur Perisi', genre: 'fantasy', style: 'pastel', age: '4-6', language: 'tr' },
  { characters: ['Uçan Ada Sakinleri', 'Rüzgar Gülü'], prompt: 'Ada sakinleri, adalarının rüzgarda çok sallandığını görünce dev bir rüzgar gülü inşa ederler.', voice: 'Iapetus', voiceName: 'Orman Muhafızı', genre: 'fantasy', style: 'pixar', age: '10-13', language: 'tr' },
  { characters: ['Sihirli Değnek', 'Sakıncalı Büyücü'], prompt: 'Değnek, yanlışlıkla her dokunduğunu dondurmaya başlayınca büyücü onu ısıtmak için güneşle anlaşır.', voice: 'Algieba', voiceName: 'Cesur Şövalye', genre: 'fantasy', style: 'retro', age: '6-10', language: 'tr' },
  
  // --- ENGLISH SCENARIOS ---
  { characters: ['Space Explorer Tom', 'Robot Buddy'], prompt: 'Tom and Robot Buddy discover a planet made entirely of chocolate and must find the Golden Cocoa Bean.', voice: 'Algenib', voiceName: 'Traveler Rabbit', genre: 'sci_fi', style: 'pixar', age: '6-10', language: 'en' },
  { characters: ['Princess Lily', 'Sparkle the Unicorn'], prompt: 'Princess Lily and Sparkle go on a quest to find the lost rainbow crystal to save the Magic Kingdom.', voice: 'Gacrux', voiceName: 'Mysterious Princess', genre: 'fantasy', style: 'watercolor', age: '4-6', language: 'en' },
  { characters: ['Detective Max', 'Whisker the Cat'], prompt: 'Max and Whisker solve the mystery of the missing moonlight in the Sleepy Hollow town.', voice: 'Callirrhoe', voiceName: 'Storyteller Woman', genre: 'adventure', style: 'cartoon', age: '10-13', language: 'en' },

  // --- ADDITIONAL ENGLISH SCENARIOS ---
  { characters: ['Oliver the Otter', 'Sparky the Fish'], prompt: 'Oliver and Sparky find a sunken pirate ship and search for the legendary Golden Pearl.', voice: 'Algenib', voiceName: 'Traveler Rabbit', genre: 'adventure', style: 'watercolor', age: '4-6', language: 'en' },
  { characters: ['Robot Z-4', 'Maya the Inventor'], prompt: 'Maya builds a new wing for Z-4, and they fly to the floating islands of Cloudia.', voice: 'Iapetus', voiceName: 'Forest Guardian', genre: 'sci_fi', style: 'pixar', age: '6-10', language: 'en' },
  { characters: ['Leo the Lion', 'Tiny Mouse'], prompt: 'Leo gets a thorn in his paw, and his tiny friend shows that true bravery comes in all sizes.', voice: 'Alnilam', voiceName: 'Grand King', genre: 'fable', style: 'oil', age: '2-4', language: 'en' },
  { characters: ['Sofia the Space Scout', 'Starry the Comet'], prompt: 'Sofia hitches a ride on Starry to see the rings of Saturn up close for her school project.', voice: 'Kore', voiceName: 'Rainbow Girl', genre: 'sci_fi', style: 'anime', age: '6-10', language: 'en' },
  { characters: ['Bento the Bear', 'Luna the Owl'], prompt: 'Bento is afraid of the dark, so Luna teaches him how to follow the constellations home.', voice: 'Aoede', voiceName: 'Wise Mother', genre: 'tale', style: 'pastel', age: '1-2', language: 'en' },
  { characters: ['Captain Barnaby', 'Polly the Parrot'], prompt: 'Captain Barnaby loses his compass and must rely on Polly’s songs to find the way to Treasure Island.', voice: 'Algieba', voiceName: 'Brave Knight', genre: 'adventure', style: 'retro', age: '4-6', language: 'en' },
  { characters: ['Milo the Monkey', 'Banana the Elephant'], prompt: 'Milo and Banana accidentally trigger a magical fruit rain in the middle of the jungle.', voice: 'Charon', voiceName: 'Excited Dad', genre: 'fantasy', style: 'pop_art', age: '2-4', language: 'en' },
  { characters: ['Elara the Elf', 'Willow the Deer'], prompt: 'Elara must find the Silver Leaf to heal the Great Tree before the winter frost arrives.', voice: 'Despina', voiceName: 'Serenity Fairy', genre: 'fantasy', style: 'watercolor', age: '6-10', language: 'en' },
  { characters: ['Timmy the Turtle', 'Turbo the Snail'], prompt: 'Timmy and Turbo enter the Great Slow Race, learning that the journey is more important than the finish line.', voice: 'Achird', voiceName: 'Wise Grandpa', genre: 'fable', style: 'cartoon', age: '4-6', language: 'en' },
  { characters: ['Astra the Alien', 'Kevin the Human'], prompt: 'Astra visits Earth for the first time and thinks that ice cream is a magical power source.', voice: 'Fenrir', voiceName: 'Magic Fairy', genre: 'sci_fi', style: 'pixar', age: '6-10', language: 'en' },
  { characters: ['Sir Galahad', 'Dragon Flame'], prompt: 'Sir Galahad finds out that the dragon isn’t scary—he just has a very bad case of the hiccups.', voice: 'Algieba', voiceName: 'Brave Knight', genre: 'fantasy', style: 'oil', age: '6-10', language: 'en' },
  { characters: ['Zoe the Zoologist', 'Pip the Penguin'], prompt: 'Zoe helps Pip find his way back to his family after a giant ice cube carries him out to sea.', voice: 'Callirrhoe', voiceName: 'Storyteller Woman', genre: 'adventure', style: 'anime', age: '4-6', language: 'en' }
]
